AppBundle\Entity\Userscenario:
    type: entity
    table: user_scenario
    manyToOne:
        scenario:
            targetEntity: Scenario
            inversedBy: user_scenarios
            nullable: false
            joinColumn:
                name: scenario_id
                referencedColumnName: id
        user_campaigns:
            targetEntity: Usercampaign
            inversedBy: user_scenarios
            joinColumn:
                name: user_campaign_id
                referencedColumnName: id
        userscenarioinvestigators:
            targetEntity: Userscenarioinvestigator
            orderBy: {'id':'ASC'}
            mappedBy: userscenario
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO


                    